vm:
  - size: 1G
  - volume_size: 28G
environment:
  TEST_VAL=42
ready_wait:
  120
post_install:
  stuff-service:
    - echo hello world
    - echo TEST_VAL is $TEST_VAL
    - echo domain is $DYNDEPLOY_DOMAIN
compose_files:
  name1:
    filename:
      docker-compose-alternate.yml
    context_path:
      './'
  name2:
    filename:
      Dockerfile-alternate
    context_path:
      './stuff'
no_default_compose_file:
  true
context_path:
  './stuff'
dockerfileonly:
  false
port_forwarding:
  true
non_bash_commands:
  false
