deployments:
  default:
    vm_size: 1G
    environment:
      TEST_VAL=42
    ready_wait: 120
    backend_wait: 20
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    auto_deploy_post_launch_commands:
      default:
        - echo true
        - python ./selenium_test.py
  branch:
    vm_size: 1
    vm_storage_gb: 10
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: false
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
    auto_deploy_post_launch_commands:
      default:
        - python ./selenium_test.py
