deployments:
  AcmeApp:
    vm_size: 1
    vm_storage_gb: 10
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
  
