environment:
  TEST_VAL=42
ready_wait:
  120
compose_files:
  branch:
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
post_launch:
  - target: 'stuff-service'
    command: exec
    docker: true
    options: '-it {target} echo domain is $SQUASH_DOMAIN'
  - target: 'stuff-service'
    command: exec
    docker: true
    options: '-it {target} echo branch id is $SQUASH_BRANCH_WITH_ID'
  - target: 'stuff-service'
    command: exec
    docker: true
    options: '-it {target} echo TEST_VAL2 is $TEST_VAL2'
  - target: 'stuff-service'
    command: exec
    docker: true
    options: '-it {target} echo TEST_VAL is $TEST_VAL'
