version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    subdomain_port_mapping:
      - test:81
      - another-test:8000
    environment:
      - TEST_VAL
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
