version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - TEST_VAL
      - TEST_VAL2=${SQUASH_BRANCH_WITH_ID}
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
